local v1 = { "Angel", "Autist", "Autistic", "Autism", "Ayanami", "Baratheon", "Brando", "Buddha", "Cujoh", "Christ", "Demon", "Devil", "Emiya", "Einzbern", "Elric", "Freecss", "Furry", "Gay", "God", "Goddess", "Gryffindor", "Griffindor", "Haruno", "Higashikata", "Hufflepuff", "Hyuga", "Hyuuga", "Ichigo", "Ikari", "Ilyria", "Iqar", "Jesus", "Joestar", "Kakashi", "Kekistan", "Kiryuin", "Kuchiki", "Kujo", "Kurosaki", "Mudock", "Yatho", "Kurta", "Lannister", "LGBT", "Libtard", "Locksea", "Luffy", "Matoi", "Mohammed", "Mohammud", "Mohamed", "Mohammad", "Mustang", "Nostrade", "Naruto", "Nelaria", "Niger", "Nigeria", "Nigerian", "Otsutsuki", "Rart", "Ravenclaw", "Roselia", "Sasuke", "Satan", "Senju", "Moneymark", "Slytherin", "Soryu", "Speedwagon", "Stark", "Sutemos", "Targaryen", "Tiiyenu", "Triggered", "Uchiha", "Uzumaki", "Zeppeli", "Zepperi", "Zoldyck" }
local v2 = {}
for v3 = 1, #v1 do
	v2[v1[v3]] = true
end
return v2