return {
	alias = {
		arena = "arena",
		desert = "desert",
		["sea of dust"] = "desert", 
		snowfield = "tundra", 
		snowfields = "tundra", 
		["castle sanctuary"] = "sigil", 
		["sleeping snail"] = "snail", 
		["royal wood"] = "forest", 
		["royal woods"] = "forest", 
		["sleeping forest"] = "deepforest", 
		["castle in the sky"] = "skycastle",
		["atk's expanse"] = "expanse",
		norpa = "norp",
		greenroom = "gren",
		sunken = "sunken",
		shrine = "shrine"
	},
}